# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  build:
    context: ../../.
    dockerfile: Dockerfile.test
  command: server http://minio{1...4}/data{1...3}
  env_file:
    - ./minio.env
  expose:
    - "9000"
    - "9001"

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  set-vol-ownership:
    image: registry.access.redhat.com/ubi9/ubi-micro:latest
    user: "root"
    group_add:
      - '1000'
    volumes:
      - data1-1:/tmp/s/1-1
      - data1-2:/tmp/s/1-2
      - data1-3:/tmp/s/1-3

      - data2-1:/tmp/s/2-1
      - data2-2:/tmp/s/2-2
      - data2-3:/tmp/s/2-3
      
      - data3-1:/tmp/s/3-1
      - data3-2:/tmp/s/3-2
      - data3-3:/tmp/s/3-3
      
      - data4-1:/tmp/s/4-1
      - data4-2:/tmp/s/4-2
      - data4-3:/tmp/s/4-3

    command: chown -R 1000:1000 /tmp/s/

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
      - data1-3:/data3
    depends_on:
      set-vol-ownership:
        condition: service_completed_successfully

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
      - data2-3:/data3
    depends_on:
      set-vol-ownership:
        condition: service_completed_successfully

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2
      - data3-3:/data3
    depends_on:
      set-vol-ownership:
        condition: service_completed_successfully

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2
      - data4-3:/data3
    depends_on:
      set-vol-ownership:
        condition: service_completed_successfully

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "9000:9000"
    - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data1-3:
  data2-1:
  data2-2:
  data2-3:
  data3-1:
  data3-2:
  data3-3:
  data4-1:
  data4-2:
  data4-3:
